# Generated by Django 5.1.2 on 2025-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pedido', models.CharField(max_length=100)),
                ('pagamento', models.CharField(max_length=20)),
            ],
        ),
    ]
