# Generated by Django 5.1.2 on 2025-04-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
