# Generated by Django 5.1.2 on 2025-04-22 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_comanda_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='pedido',
        ),
        migrations.AlterField(
            model_name='comanda',
            name='pagamento',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comandas.comanda')),
            ],
        ),
    ]
