# Generated by Django 5.1.2 on 2025-04-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0003_remove_comanda_pedido_alter_comanda_pagamento_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='pagamento',
        ),
        migrations.AddField(
            model_name='comanda',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao', 'Cartão')], default='pix', max_length=20),
            preserve_default=False,
        ),
    ]
