# Generated by Django 5.1.2 on 2025-04-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0004_remove_comanda_pagamento_comanda_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='pedido',
            field=models.CharField(default='Hamburguer + Suco', max_length=100),
            preserve_default=False,
        ),
    ]
